import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

// THREE-LAYER BRAND DISCOVERY
//
// Layer 1 — Seed-based: pull approved brands from the DB and use them as taste
// signals. Tells Exa "find me brands like these" — anchors on real curatorial
// decisions rather than abstract keyword guesses. Automatically improves as
// the catalog grows.
//
// Layer 2 — Editorial: search Highsnobiety, Monocle, GQ, Hypebeast, and similar
// publications for brand mentions in their "best of" / discovery content. These
// publications do curatorial work aligned with Trove's taste — surfacing brands
// they've featured is much stronger signal than keyword queries.
//
// Layer 3 — Keyword fallback: category-specific quality-first queries, focused
// on craft/heritage/premium positioning. Runs last so it fills gaps the first
// two layers miss, not as primary signal.
//
// Rejected brands from the DB are passed as anti-examples into every Exa prompt
// so the model learns from what Sam has already turned down.
//
// TASTE PROFILE — approved and rejected brands both carry matched_categories,
// matched_styles, and (for rejections) judge_reasoning, generated by the judge
// in catalog-intake and stored on every brand row. Previously none of that
// reached this function: positive signal was a random sample of ~16 approved
// brand *names*, and negative signal was the last 10-12 rejected brand names
// with no reasoning — so review decisions barely compounded into better
// discovery. buildTasteProfile() aggregates category/style frequency across
// the whole approved set (deterministic, no LLM). summarizeRejectionPatterns()
// distills recurring rejection reasoning into a handful of traits to avoid —
// one Claude call per run, not per brand or per query, reused everywhere.

const FETCH_TIMEOUT_MS = 12000;
function fetchWithTimeout(url: string, init: RequestInit = {}) {
  return fetch(url, { ...init, signal: AbortSignal.timeout(FETCH_TIMEOUT_MS) });
}
function sleep(ms: number) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

interface Candidate {
  name: string;
  domain: string;
  source: 'hand_picked' | 'seed' | 'editorial' | 'keyword' | 'nuuly';
}

function cleanDomain(raw: string): string {
  return (raw ?? '').toLowerCase().trim()
    .replace(/^https?:\/\//, '')
    .replace(/^www\./, '')
    .replace(/\/.*$/, '');
}

// Deterministic frequency count across the WHOLE approved set — not a random
// sample, so it keeps reflecting the real catalog as it grows past what fits
// in a single prompt's brand-name list.
function buildTasteProfile(approved: { matched_categories?: string[] | null; matched_styles?: string[] | null }[]): string {
  const categoryCounts = new Map<string, number>();
  const styleCounts = new Map<string, number>();
  for (const b of approved) {
    for (const c of b.matched_categories ?? []) categoryCounts.set(c, (categoryCounts.get(c) ?? 0) + 1);
    for (const s of b.matched_styles ?? []) styleCounts.set(s, (styleCounts.get(s) ?? 0) + 1);
  }
  const top = (m: Map<string, number>, n: number) =>
    [...m.entries()].sort((a, b) => b[1] - a[1]).slice(0, n).map(([k]) => k);
  const categories = top(categoryCounts, 8);
  const styles = top(styleCounts, 10);
  if (categories.length === 0 && styles.length === 0) return '';
  return `The approved catalog skews toward these categories: ${categories.join(', ')}. Recurring style/aesthetic tags: ${styles.join(', ')}.`;
}

// One Claude call per discover-brands run (not per layer, not per brand) that
// distills actual judge_reasoning from rejected brands into recurring traits
// to avoid — turns "sounds like a name we rejected" into "has the qualities
// we've actually been rejecting for."
async function summarizeRejectionPatterns(
  anthropicKey: string,
  rejected: { name: string; judge_reasoning?: string | null; rejection_note?: string | null }[],
): Promise<string> {
  // rejection_note is Sam's own reason for a manual override and takes
  // priority — judge_reasoning on a brand that reached the review queue
  // argues FOR it (an approve verdict), so using it as rejection signal on
  // a brand Sam then rejected was actively backwards. Fall back to
  // judge_reasoning only for brands the AI itself auto-rejected, where it's
  // genuine anti-signal.
  const withReasoning = rejected
    .map(b => ({ name: b.name, reason: b.rejection_note || b.judge_reasoning }))
    .filter((b): b is { name: string; reason: string } => !!b.reason);
  if (withReasoning.length === 0) return '';

  const sample = withReasoning.slice(0, 60)
    .map(b => `${b.name}: ${b.reason}`)
    .join('\n');

  const prompt = `Here are brands a curated shopping app's brand judge has rejected, with the reasoning given at the time:

${sample}

Summarize the recurring PATTERNS in why brands get rejected — the underlying
traits to avoid, not a list of brand names (e.g. "mass-market pricing without
a craft story", "generic template site with stock photography", "scaled into
wide wholesale and lost design specificity"). 3-6 short phrases, no brand names.

Respond with ONLY a JSON array of strings, no other text.`;

  try {
    const res = await fetchWithTimeout('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'x-api-key': anthropicKey, 'anthropic-version': '2023-06-01' },
      body: JSON.stringify({ model: 'claude-haiku-4-5-20251001', max_tokens: 400, messages: [{ role: 'user', content: prompt }] }),
    });
    if (!res.ok) return '';
    const data = await res.json();
    const text = data.content?.[0]?.text ?? '[]';
    const match = text.match(/\[[\s\S]*\]/);
    const patterns: string[] = match ? JSON.parse(match[0]) : [];
    return patterns.join('; ');
  } catch {
    return '';
  }
}

// ─── LAYER 0: HAND-PICKED BRAND SEEDS ───────────────────────────────────────
// For each brand Sam has explicitly hand-picked, run a dedicated single-brand
// Exa search. These are the strongest possible taste signal — not random
// clusters of approved brands, but the specific labels Sam has curated.
// Runs one search per brand in parallel (no cluster budget to worry about).

async function discoverFromHandPicked(
  exaKey: string,
  handPickedBrands: { name: string; domain: string }[],
  rejectedNames: string[],
  rejectionPatterns: string,
  knownDomains: Set<string>,
): Promise<Candidate[]> {
  if (handPickedBrands.length === 0) return [];
  const results = await Promise.allSettled(
    handPickedBrands.map(brand =>
      searchExaStorefronts(
        exaKey,
        `independent brand with the same aesthetic, craft quality, and downtown point of view as ${brand.name} — same vibe, DTC, founder-led, not mall-owned or mass-distributed`,
        rejectedNames,
        rejectionPatterns,
      ).then(found =>
        found
          .filter(b => !knownDomains.has(b.domain))
          .map(b => ({ ...b, source: 'hand_picked' as const })),
      ),
    ),
  );
  const candidates: Candidate[] = [];
  for (const result of results) {
    if (result.status === 'fulfilled') candidates.push(...result.value);
  }
  return candidates;
}

// ─── LAYER 1: SEED-BASED ────────────────────────────────────────────────────

async function discoverFromSeeds(
  exaKey: string,
  approved: { name: string; domain: string }[],
  rejectedNames: string[],
  rejectionPatterns: string,
  tasteProfile: string,
  knownDomains: Set<string>,
): Promise<Candidate[]> {
  if (approved.length === 0) return [];

  // Shuffle so different clusters surface each weekly run
  const shuffled = [...approved].sort(() => Math.random() - 0.5);

  // Build clusters of 4–5 brands each, cap at 4 clusters to stay in budget
  const CLUSTER_SIZE = 4;
  const clusters: typeof approved[] = [];
  for (let i = 0; i < Math.min(shuffled.length, CLUSTER_SIZE * 4); i += CLUSTER_SIZE) {
    clusters.push(shuffled.slice(i, i + CLUSTER_SIZE));
  }

  const profileClause = tasteProfile ? ` ${tasteProfile}` : '';
  const candidates: Candidate[] = [];
  for (const cluster of clusters) {
    const seedNames = cluster.map(b => b.name).join(', ');
    try {
      const found = await searchExaStorefronts(
        exaKey,
        `independent brand with the same cool, considered, craft-driven downtown aesthetic and customer as ${seedNames} — small team or founder story, strong visual identity, direct-to-consumer, not mall-owned or mass-distributed.${profileClause}`,
        rejectedNames,
        rejectionPatterns,
      );
      for (const b of found) {
        if (!knownDomains.has(b.domain)) candidates.push({ ...b, source: 'seed' });
      }
    } catch { /* skip failed cluster, continue */ }
  }
  return candidates;
}

// ─── LAYER 2: EDITORIAL ─────────────────────────────────────────────────────

// Publications that Trove's customer actually reads — editorial whose curatorial
// taste maps to "downtown, craft-driven, cool" rather than luxury or fast fashion.
const EDITORIAL_SEARCHES: { query: string; domains: string[] }[] = [
  {
    // The core discovery pipe: Highsnobiety and GQ's best-new-brand coverage
    // skews exactly toward the ALD/Bode/Noah NYC tier
    query: 'best new independent menswear brands to know 2026 downtown cool craft',
    domains: ['highsnobiety.com', 'gq.com', 'esquire.com'],
  },
  {
    // Hypebeast covers the streetwear/prep-adjacent persona (ALD, Rowing Blazers,
    // Cherry LA tier) without drifting into pure hype/resale culture
    query: 'best independent streetwear brands quality craft considered cool 2026',
    domains: ['hypebeast.com', 'highsnobiety.com'],
  },
  {
    // Women's side of the same customer — Sporty & Rich, Dôen, Alex Crane tier
    query: 'best independent womenswear brands downtown elevated cool off-duty considered',
    domains: ['whowhatwear.com', 'gq.com', 'highsnobiety.com'],
  },
  {
    // Craft/heritage rabbit hole — 3sixteen, Imogene & Willie, Taylor Stitch tier
    query: 'best craft heritage workwear denim brands independent small batch quality story',
    domains: ['gq.com', 'esquire.com', 'highsnobiety.com'],
  },
  {
    // Wallpaper and Monocle surface design-obsessed brands with a visual POV —
    // Toogood, Story Mfg., Kapital-adjacent
    query: 'best independent fashion design brands considered craft point of view editorial',
    domains: ['wallpaper.com', 'monocle.com', 'kinfolk.com'],
  },
  {
    // Cool Hunting and similar surfaces the culturally-active, drop-driven
    // independent label scene before it hits mainstream coverage
    query: 'cool new independent brand drop limited release quality lifestyle 2026',
    domains: ['coolhunting.com', 'hypebeast.com', 'highsnobiety.com'],
  },
  // --- Real discussion/recommendation signal, not just top-down "best of"
  // editorial lists — what people are actually recommending to each other.
  {
    // r/malefashionadvice and r/streetwear recommendation threads surface
    // brands well before they hit formal editorial coverage.
    query: 'best independent menswear brand recommendation quality worth it',
    domains: ['reddit.com'],
  },
  {
    query: 'best independent womenswear brand recommendation quality worth it',
    domains: ['reddit.com'],
  },
  {
    // Substack/newsletter writers covering menswear/womenswear do the same
    // curatorial work as editorial staff, often earlier and more specifically.
    query: 'independent brand recommendation newsletter menswear womenswear discovery quality',
    domains: ['substack.com'],
  },
  {
    // Unrestricted — no domain allowlist, so this can surface whatever's
    // actually indexed (blogs, roundups, social-adjacent writeups) about a
    // brand gaining real traction right now, not just brands already on a
    // fixed publication's radar.
    query: 'independent fashion brand gaining popularity right now cult following 2026',
    domains: [],
  },
  // --- Dedicated American lane, alongside (not replacing) the international-
  // friendly searches above — Sam's customer base is US-based, so American
  // brands should have guaranteed representation even though brands from
  // elsewhere are welcome too.
  {
    query: 'best independent American-made menswear and womenswear brands downtown craft small batch 2026',
    domains: ['gq.com', 'highsnobiety.com', 'esquire.com'],
  },
  {
    query: 'best independent American brand recommendation made in USA quality worth it',
    domains: ['reddit.com'],
  },
];

// One editorial/social query end-to-end: search -> extract brand names ->
// verify each via a real Exa search (not a guessed domain). Runs entirely
// independently per query so discoverFromEditorial can run all of them
// concurrently instead of summing their latency.
async function runEditorialQuery(
  exaKey: string,
  anthropicKey: string,
  query: string,
  domains: string[],
  knownDomains: Set<string>,
  antiExamplesBlock: string,
): Promise<Candidate[]> {
  try {
    const res = await fetchWithTimeout('https://api.exa.ai/search', {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'x-api-key': exaKey },
      body: JSON.stringify({
        query,
        type: 'neural',
        numResults: 5,
        ...(domains.length > 0 ? { includeDomains: domains } : {}),
        contents: { text: { maxCharacters: 3000 } },
      }),
    });
    if (!res.ok) return [];
    const data = await res.json();
    const articles = (data.results ?? []) as { url: string; text?: string }[];
    if (!articles.length) return [];

    const combinedText = articles
      .map(a => `SOURCE: ${a.url}\n${a.text ?? ''}`)
      .join('\n\n---\n\n')
      .slice(0, 8000);
    if (!combinedText.trim()) return [];

    const extractRes = await fetchWithTimeout('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'x-api-key': anthropicKey, 'anthropic-version': '2023-06-01' },
      body: JSON.stringify({
        model: 'claude-haiku-4-5-20251001',
        max_tokens: 800,
        messages: [{
          role: 'user',
          content: `Extract independent fashion/lifestyle brand names mentioned in this content — including brands that come up in discussion/recommendation threads, not just formal "best of" lists. Only include actual brands (not publications, department stores, forums, or multi-brand retailers).${antiExamplesBlock}

Content:
${combinedText}

Respond ONLY with a JSON array of brand names — no other text:
["Brand Name", ...]

If no qualifying brands found, respond with [].`,
        }],
      }),
    });
    if (!extractRes.ok) return [];
    const extractData = await extractRes.json();
    const text = extractData.content?.[0]?.text ?? '[]';
    const match = text.match(/\[[\s\S]*\]/);
    if (!match) return [];

    // Capped at 8 — each name below costs its own Exa call (resolveDomainForBrand).
    const names: string[] = JSON.parse(match[0]).slice(0, 8);
    const candidates: Candidate[] = [];
    for (const name of names) {
      if (!name) continue;
      await sleep(300);
      const domain = await resolveDomainForBrand(exaKey, name);
      if (domain && !knownDomains.has(domain)) {
        candidates.push({ name, domain, source: 'editorial' });
      }
    }
    return candidates;
  } catch {
    return [];
  }
}

async function discoverFromEditorial(
  exaKey: string,
  anthropicKey: string,
  knownDomains: Set<string>,
  rejectedNames: string[],
  rejectionPatterns: string,
): Promise<Candidate[]> {
  const antiExamples = [
    rejectedNames.length > 0
      ? `Do NOT include brands similar to these already-rejected examples: ${rejectedNames.slice(0, 12).join(', ')}.`
      : '',
    rejectionPatterns
      ? `Also avoid brands with these traits that have gotten brands rejected before: ${rejectionPatterns}.`
      : '',
  ].filter(Boolean).join(' ');
  const antiExamplesBlock = antiExamples ? `\n\n${antiExamples}` : '';

  // All queries run concurrently — each is now a search + extraction + up
  // to 8 domain-verification calls, so summing them sequentially (the old
  // behavior) would scale total latency with the query count. Running them
  // in parallel keeps total time bounded to roughly the slowest single
  // query regardless of how many sources are in the list.
  const results = await Promise.allSettled(
    EDITORIAL_SEARCHES.map(({ query, domains }) =>
      runEditorialQuery(exaKey, anthropicKey, query, domains, knownDomains, antiExamplesBlock)),
  );

  const candidates: Candidate[] = [];
  for (const r of results) {
    if (r.status === 'fulfilled') candidates.push(...r.value);
  }
  return candidates;
}

// ─── LAYER 3: KEYWORD FALLBACK ──────────────────────────────────────────────

// Queries are written to surface the specific brand archetypes in the brief.
// Language mirrors how Trove's customer would talk about what they're looking
// for — not generic "quality premium" but specific cultural signals.
const KEYWORD_QUERIES = [
  // Downtown/design-forward menswear — Bode, Story Mfg., Corridor tier
  'independent menswear brand craft narrative small batch downtown NYC considered',
  // Streetwear/prep-adjacent — ALD, Noah NYC, Rowing Blazers tier
  'independent brand NYC prep streetwear quality collab downtown cool DTC',
  // Selvedge/heritage denim — 3sixteen, Imogene & Willie, Taylor Stitch tier
  'independent denim workwear brand Japanese selvedge heritage craft obsessive',
  // Graphic/art-adjacent — Online Ceramics, Cherry LA tier
  'independent graphic brand skate art-world cool irreverent quality DTC',
  // California coastal women's — Dôen, Alex Crane, Wellen tier
  'independent womenswear brand California coastal off-duty considered quality DTC',
  // Premium footwear with identity
  'independent footwear brand leather craft heritage quality point of view DTC',
  // Accessories/leather goods with craft story
  'independent leather goods bag brand craft heritage tannery quality small brand',
  // Drop-model / limited release labels
  'independent brand limited drop seasonal release point of view small team DTC',
  // European/international equivalent of the above
  'independent European menswear womenswear brand considered craft downtown quality',
  // Jewelry / fine accessories with identity
  'independent jewelry brand considered craft identity downtown cool DTC small studio',
  // Eyewear with a point of view
  'independent eyewear sunglasses brand craft identity considered cool DTC',
  // Hats / caps with brand identity — New Era-adjacent but independent
  'independent hat cap brand craft identity downtown cool limited DTC',
  // Bags and leather goods beyond basics
  'independent bag leather goods brand craft heritage considered identity DTC',
];

async function discoverFromKeywords(
  exaKey: string,
  rejectedNames: string[],
  rejectionPatterns: string,
  knownDomains: Set<string>,
): Promise<Candidate[]> {
  const candidates: Candidate[] = [];
  for (const query of KEYWORD_QUERIES) {
    try {
      const found = await searchExaStorefronts(exaKey, query, rejectedNames, rejectionPatterns);
      for (const b of found) {
        if (!knownDomains.has(b.domain)) candidates.push({ ...b, source: 'keyword' });
      }
    } catch { /* skip */ }
  }
  return candidates;
}

// ─── SHARED: EXA STOREFRONT SEARCH ──────────────────────────────────────────

async function searchExaStorefronts(
  apiKey: string,
  query: string,
  rejectedNames: string[],
  rejectionPatterns: string = '',
): Promise<{ name: string; domain: string }[]> {
  const antiExamples = [
    rejectedNames.length > 0
      ? ` Avoid recommending brands similar to these already-rejected examples: ${rejectedNames.slice(0, 12).join(', ')}.`
      : '',
    rejectionPatterns
      ? ` Also avoid brands with these traits that have gotten brands rejected before: ${rejectionPatterns}.`
      : '',
  ].join('');

  const res = await fetchWithTimeout('https://api.exa.ai/search', {
    method: 'POST',
    headers: { 'content-type': 'application/json', 'x-api-key': apiKey },
    body: JSON.stringify({
      query: `${query} official online store`,
      type: 'auto',
      numResults: 8,
      systemPrompt: `Return only actual brand storefronts (the brand's own site where they sell directly) — never marketplaces, department stores, multi-brand retailers, listicle articles, or social media profiles. The brand must be an independent DTC label with a clear identity and quality positioning.${antiExamples} Extract the brand's real display name and bare domain (no https://, no www, no path).`,
      outputSchema: {
        type: 'object',
        required: ['brands'],
        properties: {
          brands: {
            type: 'array',
            items: {
              type: 'object',
              required: ['name', 'domain'],
              properties: {
                name: { type: 'string', description: 'Brand display name' },
                domain: { type: 'string', description: 'Bare domain, e.g. example.com' },
              },
            },
          },
        },
      },
    }),
  });
  if (!res.ok) return [];
  const data = await res.json();
  return (data.output?.content?.brands ?? [])
    .map((b: { name?: string; domain?: string }) => ({
      name: b.name ?? '',
      domain: cleanDomain(b.domain ?? ''),
    }))
    .filter((b: { name: string; domain: string }) => b.name && b.domain);
}

// Resolves a known brand NAME to its real domain via Exa's own search +
// extraction, rather than trusting an LLM's guessed "brandname.com". The
// editorial and Nuuly layers used to ask Claude to predict a domain directly
// from a brand name mentioned in text — measured 0% of those guesses ever
// resolved to a real scrapeable storefront (42 candidates, 0 reached the
// judge), against 24–39% for layers that use Exa to find the real page.
// This function gives editorial/Nuuly the same real-search treatment.
async function resolveDomainForBrand(exaKey: string, brandName: string): Promise<string | null> {
  try {
    const res = await fetchWithTimeout('https://api.exa.ai/search', {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'x-api-key': exaKey },
      body: JSON.stringify({
        query: `${brandName} official online store`,
        type: 'auto',
        numResults: 3,
        systemPrompt: 'Return only the brand\'s own official storefront (where they sell directly) — never marketplaces, department stores, multi-brand retailers, listicle articles, or social media profiles. Extract the bare domain (no https://, no www, no path).',
        outputSchema: {
          type: 'object',
          required: ['brands'],
          properties: {
            brands: {
              type: 'array',
              items: { type: 'object', required: ['domain'], properties: { domain: { type: 'string' } } },
            },
          },
        },
      }),
    });
    if (!res.ok) return null;
    const data = await res.json();
    const domain = data.output?.content?.brands?.[0]?.domain;
    return domain ? cleanDomain(domain) : null;
  } catch {
    return null;
  }
}

// ─── LAYER 4: NUULY ─────────────────────────────────────────────────────────
//
// Nuuly (nuuly.com) carries hundreds of independent brands alongside the URBN
// family labels — it's one of the strongest external curation signals we have.
// We crawl their brands listing via Exa, extract brand slugs from URLs + page
// text, then use Claude to resolve each to a display name + likely DTC domain,
// filtering out Anthropologie/Free People/UO private labels in the same step.

async function discoverFromNuuly(
  exaKey: string,
  anthropicKey: string,
  knownDomains: Set<string>,
  rejectedNames: string[],
  rejectionPatterns: string,
): Promise<Candidate[]> {
  try {
    const res = await fetchWithTimeout('https://api.exa.ai/search', {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'x-api-key': exaKey },
      body: JSON.stringify({
        query: 'fashion brands available to rent clothing',
        type: 'keyword',
        numResults: 25,
        includeDomains: ['nuuly.com'],
        contents: { text: { maxCharacters: 4000 } },
      }),
    });
    if (!res.ok) return [];
    const data = await res.json();
    const results: { url?: string; text?: string }[] = data.results ?? [];

    // Pull brand slugs from URLs like /rent/brands/{slug}
    const brandSlugs = new Set<string>();
    for (const r of results) {
      const match = r.url?.match(/\/rent\/brands\/([^/?#]+)/);
      if (match) brandSlugs.add(match[1].replace(/-/g, ' '));
    }

    const combinedText = results.map(r => r.text ?? '').join('\n').slice(0, 5000);
    if (!combinedText.trim() && brandSlugs.size === 0) return [];

    const antiExamples = [
      rejectedNames.length > 0
        ? `Do NOT include brands similar to these already-rejected examples: ${rejectedNames.slice(0, 10).join(', ')}.`
        : '',
      rejectionPatterns
        ? `Also avoid brands with these traits that have gotten brands rejected before: ${rejectionPatterns}.`
        : '',
    ].filter(Boolean).join(' ');
    const antiExamplesBlock = antiExamples ? `\n\n${antiExamples}` : '';

    const extractRes = await fetchWithTimeout('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'x-api-key': anthropicKey, 'anthropic-version': '2023-06-01' },
      body: JSON.stringify({
        model: 'claude-haiku-4-5-20251001',
        max_tokens: 1200,
        messages: [{
          role: 'user',
          content: `You are identifying independent fashion brands from Nuuly's rental catalog.

Brand slugs extracted from nuuly.com URLs: ${[...brandSlugs].join(', ') || 'see page text'}

Page text:
${combinedText}${antiExamplesBlock}

Provide each brand's display name.

SKIP these — they are URBN private labels or sub-brands, not independent:
Anthropologie, Free People, Urban Outfitters, BHLDN, Maeve, Pilcro, Cloth & Stone,
Sanctuary, Floreat, Holding Horses, Eliza J, Moon River, BB Dakota.
Also skip any brand that is obviously mass-market, fast fashion, or not DTC.

Respond ONLY with a JSON array of brand names — no other text:
["Brand Name", ...]`,
        }],
      }),
    });

    if (!extractRes.ok) return [];
    const extractData = await extractRes.json();
    const text = extractData.content?.[0]?.text ?? '[]';
    const match = text.match(/\[[\s\S]*\]/);
    if (!match) return [];

    const names: string[] = JSON.parse(match[0]).slice(0, 15);
    const candidates: Candidate[] = [];
    for (const name of names) {
      if (!name) continue;
      await sleep(300);
      const domain = await resolveDomainForBrand(exaKey, name);
      if (domain && !knownDomains.has(domain)) {
        candidates.push({ name, domain, source: 'nuuly' });
      }
    }
    return candidates;
  } catch {
    return [];
  }
}

// ─── MAIN ────────────────────────────────────────────────────────────────────


const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};
function respond(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'Content-Type': 'application/json', ...corsHeaders },
  });
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return respond({}, 200);
  try {
    const body = await req.json().catch(() => ({}));
    const exaKey = Deno.env.get('EXA_API_KEY');
    const anthropicKey = Deno.env.get('ANTHROPIC_API_KEY');
    if (!exaKey) {
      return respond({ error: 'EXA_API_KEY secret not configured' }, 500);
    }

    // Pull current brand state — all four queries in parallel. Approved and
    // rejected both now pull matched_categories/matched_styles/judge_reasoning
    // too, not just name/domain — that's the data buildTasteProfile() and
    // summarizeRejectionPatterns() turn into real steering signal below.
    const admin = createClient(Deno.env.get('SUPABASE_URL')!, Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
    const [{ data: allBrands }, { data: rejectedBrands }, { data: approvedBrands }, { data: handPickedBrands }] = await Promise.all([
      admin.from('brands').select('domain'),
      admin.from('brands').select('name, judge_reasoning, rejection_note').eq('status', 'rejected').order('created_at', { ascending: false }).limit(100),
      admin.from('brands').select('name, domain, matched_categories, matched_styles').eq('status', 'approved').limit(500),
      admin.from('brands').select('name, domain').eq('status', 'approved').eq('hand_picked', true),
    ]);

    const knownDomains = new Set((allBrands ?? []).map(b => cleanDomain(b.domain)));
    const rejected = (rejectedBrands ?? []) as { name: string; judge_reasoning?: string | null; rejection_note?: string | null }[];
    const rejectedNames = rejected.map(b => b.name).filter(Boolean);
    const approved = (approvedBrands ?? []) as { name: string; domain: string; matched_categories?: string[] | null; matched_styles?: string[] | null }[];
    const handPicked = (handPickedBrands ?? []) as { name: string; domain: string }[];

    const tasteProfile = buildTasteProfile(approved);
    const rejectionPatterns = anthropicKey ? await summarizeRejectionPatterns(anthropicKey, rejected) : '';

    // { "custom_query": "..." } runs ONE ad-hoc themed Exa search — for
    // cheaply testing a hunch about a specific aesthetic ("New England
    // heritage prep") before deciding it's worth a permanent layer.
    // Short-circuits everything else, same isolation idea as
    // only_hand_picked, so a few exploratory pulls don't also pay for the
    // seed/editorial/keyword layers every time.
    if (typeof body.custom_query === 'string' && body.custom_query.trim()) {
      const found = await searchExaStorefronts(exaKey, body.custom_query.trim(), rejectedNames, rejectionPatterns);
      const candidates = found
        .map(b => ({ ...b, domain: cleanDomain(b.domain), source: 'custom' as const }))
        .filter(c => c.domain && !knownDomains.has(c.domain));
      return respond({ found_new: candidates.length, breakdown: { custom: candidates.length }, candidates });
    }

    // { "only_hand_picked": true } skips every layer except layer 0 — for
    // cheaply exploring what similarity search against just the hand-picked
    // list finds, without also paying for (and having to filter out) the
    // seed/editorial/keyword/nuuly layers' Exa + Anthropic calls.
    const onlyHandPicked = !!body.only_hand_picked;

    // Layers 0, 1, 2 run every time; Layer 4 (Nuuly) was a one-time bootstrap
    // source, not meant to carry ongoing weight — only runs when explicitly
    // requested via { "include_nuuly": true }, not on every regular call.
    const [handPickedCandidates, seedCandidates, editorialCandidates, nuulyCandidates] = await Promise.all([
      discoverFromHandPicked(exaKey, handPicked, rejectedNames, rejectionPatterns, knownDomains),
      onlyHandPicked
        ? Promise.resolve([] as Candidate[])
        : discoverFromSeeds(exaKey, approved, rejectedNames, rejectionPatterns, tasteProfile, knownDomains),
      !onlyHandPicked && anthropicKey
        ? discoverFromEditorial(exaKey, anthropicKey, knownDomains, rejectedNames, rejectionPatterns)
        : Promise.resolve([] as Candidate[]),
      !onlyHandPicked && anthropicKey && body.include_nuuly
        ? discoverFromNuuly(exaKey, anthropicKey, knownDomains, rejectedNames, rejectionPatterns)
        : Promise.resolve([] as Candidate[]),
    ]);

    // Layer 3: keyword fallback — exclude anything layers 0+1+2+4 already found
    const alreadyFound = new Set([
      ...knownDomains,
      ...handPickedCandidates.map(c => c.domain),
      ...seedCandidates.map(c => c.domain),
      ...editorialCandidates.map(c => c.domain),
      ...nuulyCandidates.map(c => c.domain),
    ]);
    const keywordCandidates = onlyHandPicked
      ? []
      : await discoverFromKeywords(exaKey, rejectedNames, rejectionPatterns, alreadyFound);

    // Final dedup — hand-picked candidates first (highest signal, so they win any domain collision)
    const seenDomains = new Set<string>();
    const candidates: Candidate[] = [];
    for (const c of [...handPickedCandidates, ...seedCandidates, ...editorialCandidates, ...nuulyCandidates, ...keywordCandidates]) {
      const domain = cleanDomain(c.domain);
      if (!domain || seenDomains.has(domain) || knownDomains.has(domain)) continue;
      seenDomains.add(domain);
      candidates.push({ ...c, domain });
    }

    return respond({
      found_new: candidates.length,
      breakdown: {
        hand_picked: handPickedCandidates.filter(c => !knownDomains.has(c.domain)).length,
        seed:        seedCandidates.filter(c => !knownDomains.has(c.domain)).length,
        editorial:   editorialCandidates.filter(c => !knownDomains.has(c.domain)).length,
        nuuly:       nuulyCandidates.filter(c => !knownDomains.has(c.domain)).length,
        keyword:     keywordCandidates.filter(c => !knownDomains.has(c.domain)).length,
      },
      context: {
        approved_seeds: approved.length,
        hand_picked_seeds: handPicked.length,
        rejected_anti_examples: rejectedNames.length,
        editorial_enabled: !!anthropicKey,
        taste_profile: tasteProfile || null,
        rejection_patterns: rejectionPatterns || null,
      },
      candidates,
    });
  } catch (err) {
    return respond({ error: String(err) }, 500);
  }
});

