-- Seed: migrate the 29 hand-curated products (and their 5 source brands) from
-- mobile/src/data/products.ts into the new products/brands tables. These were
-- already manually vetted this session, so brands seed straight to 'approved'.
-- Run in: Dashboard → SQL Editor → New query → Run (after 006_products.sql)

insert into public.brands (name, domain, status, platform, approved_at)
values ('Every Other Thursday', 'everyotherthursday.com', 'approved', 'shopify', now())
on conflict (domain) do nothing;

insert into public.brands (name, domain, status, platform, approved_at)
values ('Gardenheir', 'gardenheir.com', 'approved', 'shopify', now())
on conflict (domain) do nothing;

insert into public.brands (name, domain, status, platform, approved_at)
values ('Chamula', 'chamulaoriginal.com', 'approved', 'shopify', now())
on conflict (domain) do nothing;

insert into public.brands (name, domain, status, platform, approved_at)
values ('Orée New York', 'oreenyc.com', 'approved', 'ld_json', now())
on conflict (domain) do nothing;

insert into public.brands (name, domain, status, platform, approved_at)
values ('Nécessaire', 'necessaire.com', 'approved', 'shopify', now())
on conflict (domain) do nothing;

insert into public.products (id, brand_id, brand, name, price, image, ratio, url, category, styles, description, source, status)
values
  ('eot-club-loafer', (select id from public.brands where domain = 'everyotherthursday.com'), 'Every Other Thursday', 'The Club Loafer', 450, 'https://cdn.shopify.com/s/files/1/0432/6450/8061/files/LoaferSide2.jpg?v=1781631237', 1.25, 'https://everyotherthursday.com/products/the-club-loafer', 'shoes', ARRAY['vintage','coastal']::text[], 'A collaboration with Morjas in Sweden. Crafted from soft Italian "Guanto" leather with no stiff lining and a collapsable heel — wearable from day one.', 'manual', 'active'),
  ('eot-relaxed-button-down', (select id from public.brands where domain = 'everyotherthursday.com'), 'Every Other Thursday', 'Relaxed Button Down in Butter Blue Stripe', 184, 'https://cdn.shopify.com/s/files/1/0432/6450/8061/files/ButterBlueStripeRDS.jpg?v=1775412290', 1.25, 'https://everyotherthursday.com/products/relaxed-dress-shirt-in-butter-blue-stripe', 'clothing', ARRAY['coastal','minimalist']::text[], 'A wardrobe classic with an EOT approach — crisp cotton shirting in a blue and faint yellow stripe, cut with a relaxed, true-to-size fit.', 'manual', 'active'),
  ('eot-linen-fatigue-pants', (select id from public.brands where domain = 'everyotherthursday.com'), 'Every Other Thursday', 'Linen Fatigue Pants', 149, 'https://cdn.shopify.com/s/files/1/0432/6450/8061/files/CreamLinenFatigues.jpg?v=1775412666', 1.25, 'https://everyotherthursday.com/products/linen-fatigue-pants', 'clothing', ARRAY['coastal','minimalist']::text[], 'Mid-weight 100% linen, cut in the standard Fatigue Pant silhouette with patch pockets, custom branded buttons, and a high rise, straight leg.', 'manual', 'active'),
  ('eot-leather-max-bag', (select id from public.brands where domain = 'everyotherthursday.com'), 'Every Other Thursday', 'Leather Max Bag', 329, 'https://cdn.shopify.com/s/files/1/0432/6450/8061/files/MaxBagfrontbrown_e13783c5-a536-411b-bfe9-1e9293e47a9c.jpg?v=1771346034', 1.25, 'https://everyotherthursday.com/products/leather-max-bag', 'bags', ARRAY['vintage','minimalist']::text[], 'The daily driver. Genuine leather with a tumbled, worn-in treatment — large enough for a laptop and all your daily essentials.', 'manual', 'active'),
  ('eot-cashmere-vneck', (select id from public.brands where domain = 'everyotherthursday.com'), 'Every Other Thursday', 'Cashmere V-Neck Knit', 234, 'https://cdn.shopify.com/s/files/1/0432/6450/8061/files/Buttervneck.jpg?v=1775413114', 1.25, 'https://everyotherthursday.com/products/cashmere-v-neck-knit', 'clothing', ARRAY['minimalist','coastal']::text[], 'A closet staple worn like an everyday sweatshirt, but made from 100% cashmere yarn that''s soft on skin and won''t irritate.', 'manual', 'active'),
  ('eot-knitted-rugby', (select id from public.brands where domain = 'everyotherthursday.com'), 'Every Other Thursday', 'Knitted Rugby Shirt', 109, 'https://cdn.shopify.com/s/files/1/0432/6450/8061/files/BlueRugby.jpg?v=1775412512', 1.25, 'https://everyotherthursday.com/products/knitted-rugby-shirt', 'clothing', ARRAY['vintage','coastal']::text[], 'A classic utilitarian sports style with a more elegant construction — knitted like a sweater in 100% cotton with a ribbed hem and open placket.', 'manual', 'active'),
  ('gh-muse-lamp', (select id from public.brands where domain = 'gardenheir.com'), 'Tala', 'The Muse 2.0 Portable Lamp in Solid Brass', 595, 'https://cdn.shopify.com/s/files/1/0720/5824/1345/files/Tala-Muse-Solid-Brass-packshot-7.jpg?v=1781626733', 1, 'https://gardenheir.com/products/portable-solid-brass-led-lantern', 'home', ARRAY['industrial','minimalist']::text[], 'An iconic British lantern reimagined for modern living — a cordless solid brass lamp, hand-polished to a rich golden finish, for table or terrace.', 'manual', 'active'),
  ('gh-hose-reel', (select id from public.brands where domain = 'gardenheir.com'), 'Claverton Cloches', 'English Garden Hose Reel', 460, 'https://cdn.shopify.com/s/files/1/0720/5824/1345/files/Garden_Hose_Reel_Timeless.webp?v=1780666895', 1, 'https://gardenheir.com/products/english-garden-hose-reel', 'home', ARRAY['cottagecore']::text[], 'High-grade stainless steel with solid hardwood handles — a refined way to store and use a garden hose, with a British Racing Green hose included.', 'manual', 'active'),
  ('gh-watering-can', (select id from public.brands where domain = 'gardenheir.com'), 'Haws England', 'Professional Series Watering Can in British Green', 98, 'https://cdn.shopify.com/s/files/1/0720/5824/1345/files/Haws-Professional-Heavy-Duty-Large-Plastic-Watering-Can-2.jpg?v=1697480377', 1, 'https://gardenheir.com/products/haws-england-professional-series-15-gallon-plastic-watering-can-in-british-green', 'home', ARRAY['cottagecore']::text[], 'The professional''s choice — a long reach watering can perfectly balanced for long sessions in the garden.', 'manual', 'active'),
  ('gh-garden-clogs', (select id from public.brands where domain = 'gardenheir.com'), 'Gardenheir', 'Italian Garden Clogs in Bluebird', 78, 'https://cdn.shopify.com/s/files/1/0720/5824/1345/files/Bluebird_1.jpg?v=1778681635', 1, 'https://gardenheir.com/products/italian-garden-clogs-in-bluebird', 'shoes', ARRAY['boho','coastal']::text[], 'Lightweight Italian clogs in a cheerful bluebird hue — as at home in the garden as they are running errands.', 'manual', 'active'),
  ('gh-work-jacket', (select id from public.brands where domain = 'gardenheir.com'), 'Le Laboureur x Gardenheir', 'Stonewashed Work Jacket in Light Denim', 188, 'https://cdn.shopify.com/s/files/1/0720/5824/1345/files/StonewashedWorkJacket_LightDenim_039.jpg?v=1780425686', 1, 'https://gardenheir.com/products/le-laboureur-x-gardenheir-stonewashed-work-jacket-in-light-denim', 'clothing', ARRAY['industrial','vintage']::text[], 'Bringing two classics together — the denim jacket and the chore coat — made in stonewashed denim from one of France''s oldest mills.', 'manual', 'active'),
  ('gh-straw-hat', (select id from public.brands where domain = 'gardenheir.com'), 'Gardenheir', 'Handwoven Toquilla Straw Hat in Camouflage', 178, 'https://cdn.shopify.com/s/files/1/0720/5824/1345/files/Toquilla-Camouflage-Hat-4.jpg?v=1723348686', 1, 'https://gardenheir.com/products/handwoven-toquilla-straw-hat-in-camouflage', 'accessories', ARRAY['coastal','boho']::text[], 'Lightweight and flexible, individually dyed in camouflage multi-tones that bridge the warm and cool seasons.', 'manual', 'active'),
  ('chamula-smile-moc', (select id from public.brands where domain = 'chamulaoriginal.com'), 'Chamula', 'Smile Moc', 198, 'https://cdn.shopify.com/s/files/1/0628/0098/6298/files/8536251M-MO-Smile-Moc-Moca.jpg?v=1773430108', 1.5, 'https://www.chamulaoriginal.com/products/m-smile-moc', 'shoes', ARRAY['boho','vintage']::text[], 'Handmade moccasins crafted one by one by Huron artisans, made exclusively from high-quality Canadian leather.', 'manual', 'active'),
  ('chamula-brasilia', (select id from public.brands where domain = 'chamulaoriginal.com'), 'Chamula', 'Brasilia', 209, 'https://cdn.shopify.com/s/files/1/0628/0098/6298/files/6110-Brasilia-Brown-2.jpg?v=1773249214', 1.5, 'https://www.chamulaoriginal.com/products/m-brasilia', 'shoes', ARRAY['vintage']::text[], 'A timeless slip-on sandal handcrafted in Mexico, woven using traditional huarache techniques passed down through generations.', 'manual', 'active'),
  ('chamula-cuff-cap', (select id from public.brands where domain = 'chamulaoriginal.com'), 'Chamula', 'Double Cuff Cap Windmill - Black', 141, 'https://cdn.shopify.com/s/files/1/0628/0098/6298/files/DOUBLE-CUFF-CAP-WINDMILL-BLACK.jpg?v=1770410944', 1.5, 'https://www.chamulaoriginal.com/products/double-cuff-cap-windmill-black', 'accessories', ARRAY['boho']::text[], 'Hand-knit from Merino wool raised on purebred sheep grazing the Mexican mountains — warm, soft, and built to last.', 'manual', 'active'),
  ('chamula-cardigan', (select id from public.brands where domain = 'chamulaoriginal.com'), 'Chamula', 'Souvenir Paisaje Zipper Cardigan - Ivory', 847, 'https://cdn.shopify.com/s/files/1/0628/0098/6298/files/SOUVENIR-PAISAJE-ZIPPER-CARDIGAN-IVORY.jpg?v=1770343464', 1.5, 'https://www.chamulaoriginal.com/products/souvenir-paisaje-zipper-cardigan-ivory', 'clothing', ARRAY['boho','maximalist']::text[], 'Hand-knit Merino wool cardigan with an intricate landscape jacquard — a statement piece native artisans knit one at a time.', 'manual', 'active'),
  ('oree-smoking-tee', (select id from public.brands where domain = 'oreenyc.com'), 'Orée New York', 'Smoking Tee', 85, 'https://static.wixstatic.com/media/5d3369_384a0bfdcffa4ad38fc295287a8361c3~mv2.jpg/v1/fit/w_500,h_500,q_90/file.jpg', 1, 'https://www.oreenyc.com/product-page/smoking-tee', 'clothing', ARRAY['streetwear','minimalist']::text[], 'A 6.5oz loop-wheeled cotton jersey tee, produced in Japan with traditional circular knitting for a soft, structured feel that improves with wear.', 'manual', 'active'),
  ('oree-crossborder-trainer', (select id from public.brands where domain = 'oreenyc.com'), 'Orée New York', 'Crossborder Trainer 0-70 Sneaker (Antique Brown)', 250, 'https://static.wixstatic.com/media/5d3369_de9ace6fc89c4631ba1b6160f71106c3~mv2.jpg/v1/fit/w_500,h_500,q_90/file.jpg', 1, 'https://www.oreenyc.com/product-page/crossborder-trainer-0-70-sneaker-antique-brown', 'shoes', ARRAY['streetwear']::text[], 'A trainer that responds to movement, creating subtle shifts in color and texture as it wears in.', 'manual', 'active'),
  ('oree-astrud-lace-up', (select id from public.brands where domain = 'oreenyc.com'), 'Orée New York', 'Astrud Leather Lace Up', 270, 'https://static.wixstatic.com/media/5d3369_0a14edf38a704dfa8144da673afe1f33~mv2.jpg/v1/fit/w_500,h_500,q_90/file.jpg', 1, 'https://www.oreenyc.com/product-page/astrud-leather-lace-up', 'shoes', ARRAY['streetwear','vintage']::text[], 'A leather lace-up built on Orée’s Cyber-Americana sensibility — rugged construction with a refined silhouette.', 'manual', 'active'),
  ('oree-military-jacket', (select id from public.brands where domain = 'oreenyc.com'), 'Orée New York', 'O-65 Military Field Jacket (Black)', 197, 'https://static.wixstatic.com/media/5d3369_983a77b79f174a26aa891ebaef0a4269~mv2.jpg/v1/fit/w_500,h_500,q_90/file.jpg', 1, 'https://www.oreenyc.com/product-page/o-65-military-jacket-black', 'clothing', ARRAY['streetwear','industrial']::text[], 'A field jacket silhouette reworked with utilitarian pockets and a clean, blacked-out finish.', 'manual', 'active'),
  ('oree-tracer-belt', (select id from public.brands where domain = 'oreenyc.com'), 'Orée New York', 'Vachetta Tracer Belt', 160, 'https://static.wixstatic.com/media/5d3369_a1465e7c74884166a41d8f064c4efd01~mv2.jpg/v1/fit/w_500,h_500,q_90/file.jpg', 1, 'https://www.oreenyc.com/product-page/vachetta-tracer-belt', 'accessories', ARRAY['streetwear']::text[], 'Vachetta leather that develops a rich patina over time — a quiet, everyday staple.', 'manual', 'active'),
  ('oree-monk-skullcap', (select id from public.brands where domain = 'oreenyc.com'), 'Orée New York', 'Monk Skullcap', 45, 'https://static.wixstatic.com/media/5d3369_f1cca41a5633428dbdfc2e12be396ca4~mv2.jpg/v1/fit/w_500,h_500,q_90/file.jpg', 1, 'https://www.oreenyc.com/product-page/monk-skullcap', 'accessories', ARRAY['streetwear','minimalist']::text[], 'A close-fit skullcap with a pared-back, monastic simplicity.', 'manual', 'active'),
  ('oree-soft-landing-tray', (select id from public.brands where domain = 'oreenyc.com'), 'Orée New York', 'Soft Landing Tray', 25, 'https://static.wixstatic.com/media/5d3369_c8c8be9b0f704c3ab0b846189f59fe41~mv2.jpg/v1/fit/w_500,h_500,q_90/file.jpg', 1, 'https://www.oreenyc.com/product-page/soft-landing-tray', 'home', ARRAY['minimalist']::text[], 'A catch-all tray for keys, change, and the rest of a daily-carry — minimal and unfussy.', 'manual', 'active'),
  ('necessaire-eucalyptus-water', (select id from public.brands where domain = 'necessaire.com'), 'Nécessaire', 'Eucalyptus Water', 35, 'https://cdn.shopify.com/s/files/1/0034/8812/0947/files/01_THEEUCALYPTUSWATER.jpg?v=1779917039', 1.17, 'https://www.necessaire.com/products/eucalyptus-water', 'beauty', ARRAY['minimalist']::text[], 'An immediate skin refresh in an ultra-fine mist that helps depleted skin feel restored, cooled, and revived.', 'manual', 'active'),
  ('necessaire-hand-duo', (select id from public.brands where domain = 'necessaire.com'), 'Nécessaire', 'The Hand Wash + The Hand Lotion', 100, 'https://cdn.shopify.com/s/files/1/0034/8812/0947/files/01_THEHANDDUO_SA.jpg?v=1778016466', 1.17, 'https://www.necessaire.com/products/the-hand-wash-lotion-duo', 'beauty', ARRAY['minimalist']::text[], 'The covetable hand duo — The Hand Wash cleanses, The Hand Lotion restores.', 'manual', 'active'),
  ('necessaire-body-exfoliator', (select id from public.brands where domain = 'necessaire.com'), 'Nécessaire', 'The Body Exfoliator', 35, 'https://cdn.shopify.com/s/files/1/0034/8812/0947/files/01_THEBODYEXFOLIATOR_SA_PDP.jpg?v=1770939118', 1.17, 'https://www.necessaire.com/products/the-body-exfoliator-santal', 'beauty', ARRAY['minimalist']::text[], 'A mild-to-moderate in-shower physical and chemical exfoliant for the body.', 'manual', 'active'),
  ('necessaire-deodorant', (select id from public.brands where domain = 'necessaire.com'), 'Nécessaire', 'The Deodorant | Mandelic Acid', 24, 'https://cdn.shopify.com/s/files/1/0034/8812/0947/files/01_THEDEODORANT_CC_1.jpg?v=1780332576', 1.17, 'https://www.necessaire.com/products/the-deodorant-mandelic-acid-cypres-citronne', 'beauty', ARRAY['minimalist']::text[], 'An extra-strength, aluminum-free deodorant in a soft-solid stick.', 'manual', 'active'),
  ('necessaire-rosemary-mask', (select id from public.brands where domain = 'necessaire.com'), 'Nécessaire', 'Rosemary Leave-In Mask', 60, 'https://cdn.shopify.com/s/files/1/0034/8812/0947/files/01_ROSEMARYMASK.jpg?v=1765906488', 1.17, 'https://www.necessaire.com/products/rosemary-leave-in-mask', 'beauty', ARRAY['minimalist','boho']::text[], 'An advanced leave-in hair treatment for use once or twice a week, formulated with rosemary extract.', 'manual', 'active'),
  ('necessaire-body-brush', (select id from public.brands where domain = 'necessaire.com'), 'Nécessaire', 'The Body Brush', 25, 'https://cdn.shopify.com/s/files/1/0034/8812/0947/files/01_TheBodyBrush_PDP.jpg?v=1761340499', 1.17, 'https://www.necessaire.com/products/the-body-brush', 'beauty', ARRAY['minimalist']::text[], 'A daily body exfoliation brush, crafted from sustainably sourced, FSC-certified beechwood.', 'manual', 'active')
on conflict (id) do nothing;

