-- ----------------------------------------------------------------
-- Trove – semantic taste engine: embeddings, brand follows, product
-- views, purchased marking, shop_for fix
-- Run in: Dashboard → SQL Editor → New query → Run
--
-- IMPORTANT: confirm the embedding dimension below (1024) matches
-- whatever Voyage model is actually used before running this — if it
-- doesn't, every embedding insert will fail with a dimension mismatch.
-- Check the model's docs at https://docs.voyageai.com/docs/embeddings
-- and adjust `vector(1024)` in two places below if needed.
-- ----------------------------------------------------------------

create extension if not exists vector;

-- Every product gets a semantic embedding of what it actually is (brand +
-- name + description), so similarity can be computed between products that
-- share no category/style tags at all but "feel" alike. Generated by
-- catalog-intake at scrape time; backfilled once for everything already in
-- the catalog via the new backfill_embeddings admin action.
alter table public.products add column if not exists embedding vector(1024);
create index if not exists products_embedding_idx on public.products
  using hnsw (embedding vector_cosine_ops);

-- Brand-level audience classification — fixes the shop_for gap. Individual
-- products have no reliable gender signal (inferring one from a product
-- name repeats the exact brittle-keyword problem already hit with category
-- backfilling), but brands themselves are reliably classifiable, and
-- catalog-intake already makes one LLM judgment call per brand anyway.
alter table public.brands add column if not exists audience text
  check (audience in ('mens', 'womens', 'unisex'));

-- "Mark as purchased" — a state change of a save, not an independent event
-- (nothing here is purchased without being saved to a board first).
alter table public.board_items add column if not exists purchased_at timestamptz;

-- board_items had read/insert/delete RLS but no update policy at all —
-- needed now that purchased_at is something the owner sets after the fact.
-- Scoped to the board owner only: marking something purchased is a
-- statement about the owner's own buying behavior, not something a
-- collaborator should set on someone else's board.
create policy "board_items_update" on public.board_items for update using (
  exists (select 1 from public.boards b where b.id = board_id and b.user_id = auth.uid())
);

-- Brand follows — doesn't exist yet, needed before anyone can follow a
-- brand. Mirrors the existing user-to-user `follows` table. Read is open
-- to everyone (not just the follower) so a brand's follower count can be
-- shown on its profile page, same as how follower counts already work on
-- user profiles today.
create table public.brand_follows (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references public.profiles(id) on delete cascade,
  brand_id   uuid not null references public.brands(id) on delete cascade,
  created_at timestamptz default now(),
  unique (user_id, brand_id)
);
create index on public.brand_follows(user_id);
create index on public.brand_follows(brand_id);

alter table public.brand_follows enable row level security;
create policy "brand_follows_read"   on public.brand_follows for select using (true);
create policy "brand_follows_insert" on public.brand_follows for insert with check (auth.uid() = user_id);
create policy "brand_follows_delete" on public.brand_follows for delete using (auth.uid() = user_id);

-- Product views — the weakest, most passive signal. One row per user per
-- product (not per visit), so repeatedly reopening the same item doesn't
-- inflate its weight relative to genuinely distinct interest.
create table public.product_views (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references public.profiles(id) on delete cascade,
  product_id text not null,
  viewed_at  timestamptz default now(),
  unique (user_id, product_id)
);
create index on public.product_views(user_id);

alter table public.product_views enable row level security;
create policy "product_views_read"   on public.product_views for select using (auth.uid() = user_id);
create policy "product_views_insert" on public.product_views for insert with check (auth.uid() = user_id);

-- ----------------------------------------------------------------
-- The ranking function. Builds a per-user "taste vector" as the average
-- embedding across their weighted behavioral signals (purchases weighted
-- heaviest via row repetition — avg() over more copies of the same vector
-- pulls the average further toward it — not via vector*scalar, since that
-- pgvector operator isn't reliably available across versions; repetition
-- via generate_series is the portable way to weight an average), then
-- ranks every active product by cosine similarity to that vector, with two
-- small discrete adjustments layered on top, then draws the final feed
-- order via weighted random sampling (Gumbel-max trick: noisy log-weight,
-- sort descending) so nothing is ever fully excluded — see plan doc for
-- why a hard sort was rejected.
--
-- Falls back to a pure shuffle (no embedding term at all) when the user
-- has no behavioral signal yet — not an approximation of cold start, the
-- literal absence of a taste vector means the similarity term is just 0
-- for everyone, so the only thing left driving order is the random jitter.
-- ----------------------------------------------------------------
-- Default limit comfortably exceeds the current catalog (~1,475 active
-- products) so a single ranked fetch covers everything — getProductById()
-- stays a synchronous in-memory lookup with no separate fallback-fetch path
-- needed for deep links. Revisit this limit if the catalog grows well past
-- a few thousand products.
create or replace function public.rank_products_for_user(p_user_id uuid, p_limit int default 2000)
returns setof public.products
language plpgsql
stable
as $$
declare
  taste_vector vector(1024);
  v_shop_for text[];
begin
  select shop_for into v_shop_for from public.profiles where id = p_user_id;

  with weighted_signals as (
    select bi.product_id
    from public.board_items bi
    join public.boards b on b.id = bi.board_id
    cross join generate_series(1, 6)
    where b.user_id = p_user_id and bi.purchased_at is not null
    union all
    select bi.product_id
    from public.board_items bi
    join public.boards b on b.id = bi.board_id
    cross join generate_series(1, 2)
    where b.user_id = p_user_id and bi.purchased_at is null
    union all
    select pr.id
    from public.brand_follows bf
    join public.products pr on pr.brand_id = bf.brand_id
    cross join generate_series(1, 3)
    where bf.user_id = p_user_id
    union all
    select pv.product_id
    from public.product_views pv
    where pv.user_id = p_user_id
  )
  select avg(p.embedding) into taste_vector
  from weighted_signals ws
  join public.products p on p.id = ws.product_id
  where p.embedding is not null;

  return query
  with scored as (
    select
      pr.*,
      (
        coalesce(
          case when taste_vector is not null and pr.embedding is not null
            then -(pr.embedding <=> taste_vector) else 0 end,
          0
        )
        + case when exists (
            select 1 from public.profiles prof
            where prof.id = p_user_id
              and (
                pr.category = any(prof.taste_categories)
                or lower(regexp_replace(pr.brand, '[^a-zA-Z0-9]+', '-', 'g')) = any(prof.taste_brands)
                or pr.styles && prof.taste_styles
              )
          ) then 1 else 0 end
        + case when v_shop_for is not null and array_length(v_shop_for, 1) > 0
            and exists (
              select 1 from public.brands b2
              where b2.id = pr.brand_id and b2.audience is not null
                and b2.audience <> 'unisex' and not (b2.audience = any(v_shop_for))
            ) then -2 else 0 end
        + case when exists (
            select 1 from public.not_interested ni
            where ni.user_id = p_user_id and ni.brand = pr.brand
          ) then -3 else 0 end
      ) as combined_score
    from public.products pr
    where pr.status = 'active'
      and pr.id not in (select product_id from public.not_interested where user_id = p_user_id)
  )
  select scored.id, scored.brand_id, scored.brand, scored.name, scored.price, scored.image, scored.ratio,
         scored.url, scored.category, scored.styles, scored.description, scored.source, scored.external_handle,
         scored.status, scored.first_seen_at, scored.last_seen_at, scored.price_history, scored.removed_at,
         scored.created_at, scored.embedding
  from scored
  order by -ln(random()) / greatest(exp(scored.combined_score / 4.0), 0.001) asc
  limit p_limit;
end;
$$;
